
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

http:
  ssl_certificate: /cert/live/tajha.duckdns.org/fullchain.pem
  ssl_key: /cert/live/tajha.duckdns.org/privkey.pem
  base_url: tajha.duckdns.org

tplink:
  discovery: false
  switch:
    - host: 192.168.86.22
    - host: 192.168.86.24
    - host: 192.168.86.25

weather:
  - platform: darksky
    api_key: c33400d66f8d6da9bc1f195d732b35f0

zwave:
  usb_path: /dev/zwave

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
